---
title: "Taux de change US/G"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(rvest)
library(dplyr)
library(shiny)
library(ggplot2)
library(xml2)
library(XML)
library(htmlTable)
library(highcharter)
library(gt)
library(htmltools)
library(viridis)

```

```{r}
#### Importation des donnees

### Taux du jours de la BRH ###### 

col_link<- "https://www.brh.ht/taux-du-jour/"
col_page<- read_html(col_link)
TdJ<- col_page%>% html_nodes("table")%>% html_table(fill = TRUE)


###rearrangement du tableau
TBRH<-as.data.frame(TdJ)
names(TBRH)<-c(" ","ACHATS","VENTES","SPREAD")
tbrh<-TBRH[-1, ]
tbrh$ACHATS<-as.numeric(as.character(tbrh$ACHATS))
tbrh$VENTES<-as.numeric(as.character(tbrh$VENTES))
tbrh$SPREAD<-as.numeric(as.character(tbrh$SPREAD))

###### Taux affiche par les autres banques #########

col_link1<- "https://www.brh.ht/taux-affiches-par-les-banques-et-les-agents-de-change-2/"
col_page1<- read_html(col_link1)
Tdb<- col_page1%>% html_nodes("table")%>% html_table(fill = TRUE)

###rearrangement du tableau
TDAB<-as.data.frame(Tdb)
names(TDAB)<-c(" ","ACHATS","VENTES","SPREAD")
tdab<-TDAB[-c(1,9), ]
tdab$ACHATS<-as.numeric(as.character(tdab$ACHATS))
tdab$VENTES<-as.numeric(as.character(tdab$VENTES))
tdab$SPREAD<-as.numeric(as.character(tdab$SPREAD))



```


Column {data-width=650}
-----------------------------------------------------------------------

### Taux du jour

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Taux des autres banques

```{r}

```

### Marche informel

```{r}

```

